name        "wework-docker"
description "Manage Docker images for wework"
maintainer  "Whitespace"
version     "0.0.2"
depends     "logrotate", "~> 1.8.0"
depends     "apt"

recipe "docker::install", "Install and setup docker"
recipe "docker::cleanup", "Removes unused images"
recipe "docker::deploy", "Deploys a docker container"
recipe "docker::registries", "Logs in to docker registries"
recipe "docker::data_volumes", "Creates data only containers"
recipe "docker::exec", "Run docker exec on a container"
recipe "docker::notify_rollbar", "Used to send post deploy notifications to rollbar"
recipe "docker::logrotate", "Sets up correct log rotation for docker containers"

depends "apt"
